# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(871, 536)
        Form.setStyleSheet("border:None;\n"
"")
        self.pushButton_update = QtWidgets.QPushButton(Form)
        self.pushButton_update.setGeometry(QtCore.QRect(740, 20, 111, 31))
        self.pushButton_update.setObjectName("pushButton_update")
        self.pushButton_search = QtWidgets.QPushButton(Form)
        self.pushButton_search.setGeometry(QtCore.QRect(750, 100, 91, 41))
        self.pushButton_search.setObjectName("pushButton_search")
        self.lineEdit_input = QtWidgets.QLineEdit(Form)
        self.lineEdit_input.setGeometry(QtCore.QRect(30, 100, 701, 41))
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.textEdit_out = QtWidgets.QTextEdit(Form)
        self.textEdit_out.setGeometry(QtCore.QRect(30, 160, 811, 371))
        self.textEdit_out.setObjectName("textEdit_out")
        self.label_title = QtWidgets.QLabel(Form)
        self.label_title.setGeometry(QtCore.QRect(240, 30, 361, 41))
        self.label_title.setStyleSheet("font: 75 28pt \"思源宋体\";")
        self.label_title.setObjectName("label_title")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_update.setText(_translate("Form", "更新数据"))
        self.pushButton_search.setText(_translate("Form", "搜  索"))
        self.label_title.setText(_translate("Form", "Linux 命令提示大全"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
